import { RiTa } from 'rita'

/**
 * A curated technical/log-specific lexicon for acrostic anchors.
 * This ensures the words blend perfectly into a terminal aesthetic.
 */
const LOG_LEXICON: Record<string, string[]> = {
  a: [
    'access',
    'archive',
    'alert',
    'audit',
    'active',
    'admin',
    'auth',
    'alarm',
    'array',
    'asset',
    'anomaly',
    'aether',
    'algorithm',
    'aperture',
    'augment',
    'avatar',
  ],
  b: [
    'buffer',
    'backup',
    'bridge',
    'binary',
    'beacon',
    'batch',
    'boot',
    'block',
    'bit',
    'bypass',
    'backlight',
    'blackbox',
    'bios',
    'breach',
    'broadcast',
  ],
  c: [
    'cipher',
    'core',
    'crypto',
    'code',
    'cluster',
    'clock',
    'command',
    'cache',
    'cell',
    'client',
    'chrome',
    'cortex',
    'console',
    'cobalt',
    'circuit',
    'carbon',
    'cloud',
  ],
  d: [
    'data',
    'debug',
    'daemon',
    'device',
    'digital',
    'drive',
    'disk',
    'downlink',
    'delta',
    'deny',
    'deck',
    'drone',
    'drift',
    'darknet',
    'decrypt',
    'ddos',
  ],
  e: [
    'entry',
    'error',
    'event',
    'echo',
    'engine',
    'export',
    'exit',
    'ethernet',
    'epoch',
    'exec',
    'edge',
    'emitter',
    'encrypt',
    'entropy',
    'ether',
  ],
  f: [
    'filter',
    'file',
    'flash',
    'flow',
    'fiber',
    'frame',
    'fault',
    'fetch',
    'flux',
    'front',
    'firewall',
    'fractal',
    'fringe',
    'frontend',
    'fusion',
  ],
  g: [
    'ghost',
    'gate',
    'grid',
    'global',
    'guard',
    'gear',
    'glitch',
    'group',
    'graph',
    'grant',
    'gravity',
    'gimbal',
  ],
  h: [
    'host',
    'header',
    'hash',
    'heart',
    'hidden',
    'handle',
    'halt',
    'hook',
    'hub',
    'hybrid',
    'haptic',
    'hologram',
    'hyper',
    'helix',
    'hypervisor',
  ],
  i: [
    'input',
    'index',
    'image',
    'info',
    'inner',
    'interface',
    'invoke',
    'io',
    'id',
    'init',
    'implant',
    'ion',
    'isotope',
    'iterate',
    'infrastructure',
  ],
  j: [
    'job',
    'join',
    'junk',
    'jumper',
    'journal',
    'jack',
    'java',
    'json',
    'jitter',
    'junction',
    'jacket',
    'jolt',
    'juice',
  ],
  k: [
    'key',
    'kernel',
    'kill',
    'knocker',
    'kilo',
    'kiosk',
    'kinetics',
    'kit',
    'knob',
    'knot',
    'kinetic',
    'k-byte',
    'keyframe',
    'klaxon',
  ],
  l: [
    'log',
    'link',
    'level',
    'loop',
    'local',
    'logic',
    'layer',
    'latency',
    'limit',
    'load',
    'laser',
    'lattice',
    'legacy',
    'lens',
    'lightspeed',
    'liquid',
    'lucid',
  ],
  m: [
    'memory',
    'master',
    'monitor',
    'matrix',
    'module',
    'mask',
    'mode',
    'meta',
    'macro',
    'map',
    'mainframe',
    'machine',
    'mace',
    'mantle',
    'mechanical',
    'media',
    'megacity',
    'mesh',
    'metal',
    'micro',
    'mimic',
    'mobile',
    'mod',
    'mono',
    'synth',
    'mutant',
  ],
  n: [
    'node',
    'network',
    'null',
    'neon',
    'noise',
    'net',
    'next',
    'nano',
    'native',
    'notify',
    'nebula',
    'nerve',
    'neural',
    'neutral',
    'neutron',
    'nexus',
    'night',
    'nitrogen',
    'nomad',
    'nova',
    'nuclear',
    'nucleus',
    'nuke',
  ],
  o: [
    'output',
    'object',
    'open',
    'offset',
    'order',
    'outer',
    'origin',
    'option',
    'os',
    'omega',
    'optic',
    'orbit',
    'organic',
    'oscillate',
    'overlay',
    'overload',
    'oxygen',
    'ozone',
  ],
  p: [
    'port',
    'protocol',
    'pulse',
    'packet',
    'proxy',
    'phantom',
    'phase',
    'process',
    'patch',
    'ping',
    'parallel',
    'parity',
    'particle',
    'peak',
    'peripheral',
    'photon',
    'pilot',
    'pin',
    'pipe',
    'pixel',
    'plasma',
    'platform',
    'plug',
    'point',
    'polar',
    'poly',
    'prism',
    'probe',
    'program',
    'project',
    'proton',
    'prototype',
    'pure',
    'purple',
    'pvc',
    'python',
  ],
  q: [
    'query',
    'queue',
    'quad',
    'quick',
    'quant',
    'quota',
    'quartz',
    'quasi',
    'quark',
    'quake',
    'quantum',
    'quasar',
    'quiet',
    'quint',
  ],
  r: [
    'remote',
    'root',
    'relay',
    'record',
    'router',
    'raw',
    'reset',
    'render',
    'range',
    'ready',
    'radar',
    'radio',
    'rapid',
    'ray',
    'reactor',
    'real',
    'reboot',
    'recall',
    'receiver',
    'recursion',
    'red',
    'reflex',
    'resonance',
    'resource',
    'response',
    'restore',
    'retinal',
    'retro',
    'reverse',
    'rhythm',
    'rig',
    'robot',
    'rocket',
    'rotor',
    'route',
    'rover',
    'ruby',
    'rule',
    'run',
  ],
  s: [
    'signal',
    'system',
    'stream',
    'sector',
    'socket',
    'shadow',
    'source',
    'state',
    'status',
    'sync',
    'satellite',
    'scan',
    'scanner',
    'scope',
    'scrap',
    'screen',
    'script',
    'scroll',
    'search',
    'secure',
    'sensor',
    'sentinel',
    'sequence',
    'serial',
    'server',
    'service',
    'session',
    'shell',
    'shield',
    'shift',
    'shock',
    'shunt',
    'shutter',
    'silicon',
    'silo',
    'silver',
    'simulation',
    'sink',
    'site',
    'skin',
    'sky',
    'slide',
    'slot',
    'smart',
    'smoke',
    'snap',
    'soft',
    'solar',
    'solid',
    'sonar',
    'sonic',
    'sound',
    'space',
    'spark',
    'spatial',
    'speed',
    'sphere',
    'spike',
    'spiral',
    'spire',
    'splice',
    'split',
    'sprawl',
    'spray',
    'spread',
    'spring',
    'sprite',
    'square',
    'stack',
    'stage',
    'stand',
    'star',
    'start',
    'static',
    'station',
    'steady',
    'steam',
    'steel',
    'stem',
    'step',
    'stereo',
    'stick',
    'still',
    'stitch',
    'stock',
    'stone',
    'stop',
    'storage',
    'storm',
    'strain',
    'street',
    'stress',
    'stretch',
    'strike',
    'string',
    'strip',
    'strobe',
    'stroke',
    'strong',
    'structure',
    'studio',
    'style',
    'sub',
    'subject',
    'submarine',
    'submerge',
    'substance',
    'subtle',
    'success',
    'suction',
    'sudden',
    'suffer',
    'sugar',
    'suit',
    'sulfate',
    'sulfur',
    'sum',
    'summer',
    'summit',
    'sun',
    'super',
    'supply',
    'support',
    'surface',
    'surge',
    'surplus',
    'survey',
    'survival',
    'suspect',
    'suspend',
    'sustain',
    'swallow',
    'swamp',
    'swarm',
    'sway',
    'swear',
    'sweat',
    'sweep',
    'sweet',
    'swell',
    'swift',
    'swim',
    'swing',
    'switch',
    'sword',
    'symbol',
    'symmetry',
    'sympathy',
    'symphony',
    'symptom',
    'syndicate',
    'synergy',
    'syntax',
    'synthesis',
  ],
  t: [
    'terminal',
    'trace',
    'target',
    'token',
    'thread',
    'tower',
    'trigger',
    'task',
    'temp',
    'tag',
    'tab',
    'table',
    'tack',
    'tactic',
    'tail',
    'take',
    'talent',
    'talk',
    'tall',
    'tank',
    'tap',
    'tape',
    'taste',
    'tax',
    'taxi',
    'tea',
    'teach',
    'team',
    'tear',
    'tech',
    'technical',
    'technology',
    'teen',
    'teeth',
    'tel',
    'tele',
    'telegram',
    'telegraph',
    'telephone',
    'telescope',
    'television',
    'tell',
    'temple',
    'temporary',
    'ten',
    'tend',
    'tender',
    'tennis',
    'tent',
    'term',
    'terrace',
    'terrain',
    'terrestrial',
    'territory',
    'terror',
    'test',
    'text',
    'texture',
    'than',
    'thank',
    'that',
    'the',
    'theater',
    'theme',
    'theory',
    'therapy',
    'there',
    'thermal',
    'thesis',
    'they',
    'thick',
    'thief',
    'thigh',
    'thin',
    'thing',
    'think',
    'third',
    'thirsty',
    'thirteen',
    'thirty',
    'this',
    'thorn',
    'thorough',
    'those',
    'though',
    'thought',
    'thousand',
    'thread',
    'threat',
    'three',
    'thresh',
    'throat',
    'through',
    'throw',
    'thrust',
    'thumb',
    'thunder',
    'thus',
    'thy',
    'thym',
    'ticket',
    'tide',
    'tidy',
    'tie',
    'tiger',
    'tight',
    'tile',
    'till',
    'tilt',
    'timber',
    'time',
    'timid',
    'tin',
    'tiny',
    'tip',
    'tire',
    'tissue',
    'title',
    'to',
    'toast',
    'tobacco',
    'today',
    'toe',
    'together',
    'toil',
    'toilet',
    'told',
    'toll',
    'tomato',
    'tomb',
    'tomorrow',
    'ton',
    'tone',
    'tongue',
    'tonight',
    'too',
    'tool',
    'tooth',
    'top',
    'topic',
    'torch',
    'tornado',
    'total',
    'touch',
    'tough',
    'tour',
    'toward',
    'towel',
    'tower',
    'town',
    'toy',
    'trace',
    'track',
    'trade',
    'traffic',
    'tragedy',
    'trail',
    'train',
    'trait',
    'tram',
    'trance',
    'transfer',
    'transform',
    'transition',
    'translate',
    'transmit',
    'trap',
    'travel',
    'tray',
    'tread',
    'treasure',
    'treat',
    'tree',
    'trek',
    'tremble',
    'trench',
    'trend',
    'trial',
    'triangle',
    'tribe',
    'trick',
    'trigger',
    'trim',
    'trio',
    'trip',
    'triple',
    'triumph',
    'troop',
    'trophy',
    'tropical',
    'trouble',
    'trough',
    'true',
    'trumpet',
    'trunk',
    'trust',
    'truth',
    'try',
    'tube',
    'tuck',
    'tuesday',
    'tuft',
    'tug',
    'tuition',
    'tulip',
    'tumble',
    'tumor',
    'tune',
    'tunnel',
    'turbine',
    'turkey',
    'turn',
    'turtle',
    'tutor',
    'twelve',
    'twenty',
    'twice',
    'twig',
    'twilight',
    'twin',
    'twist',
    'two',
    'type',
    'tyrant',
  ],
  u: [
    'uplink',
    'update',
    'user',
    'unit',
    'upload',
    'unzip',
    'unlock',
    'uri',
    'url',
    'unix',
    'ultra',
    'umbra',
    'under',
    'unify',
    'unique',
    'unit',
    'universal',
    'unknown',
    'unmask',
    'unpack',
    'unseen',
    'unstable',
    'upward',
    'urban',
    'utility',
    'uv',
  ],
  v: [
    'virtual',
    'volume',
    'void',
    'vocal',
    'vortex',
    'vector',
    'volt',
    'vessel',
    'valid',
    'value',
    'vapor',
    'variant',
    'vault',
    'veil',
    'velocity',
    'venom',
    'vent',
    'verify',
    'verge',
    'version',
    'vertical',
    'vibe',
    'video',
    'view',
    'village',
    'vinyl',
    'viral',
    'visible',
    'vision',
    'visit',
    'visual',
    'vital',
    'vivid',
    'voice',
    'volatile',
    'voltage',
    'volume',
    'voter',
    'vow',
    'voyage',
    'vulnerability',
  ],
  w: [
    'worker',
    'wire',
    'wave',
    'watch',
    'web',
    'warp',
    'wake',
    'wifi',
    'word',
    'write',
    'wall',
    'wallet',
    'wand',
    'ward',
    'warm',
    'warning',
    'warp',
    'waste',
    'water',
    'wave',
    'way',
    'weak',
    'weapon',
    'wear',
    'weather',
    'web',
    'weekly',
    'weight',
    'weird',
    'west',
    'wet',
    'whale',
    'wheat',
    'wheel',
    'where',
    'while',
    'whip',
    'white',
    'whole',
    'why',
    'wide',
    'width',
    'wild',
    'will',
    'win',
    'wind',
    'window',
    'wing',
    'wink',
    'winner',
    'winter',
    'wire',
    'wisdom',
    'wise',
    'wish',
    'wit',
    'witch',
    'with',
    'witness',
    'wolf',
    'woman',
    'wonder',
    'wood',
    'wool',
    'word',
    'work',
    'world',
    'worm',
    'worry',
    'worth',
    'would',
    'wound',
    'wrap',
    'wreck',
    'wrist',
    'write',
    'wrong',
  ],
  x: [
    'xray',
    'xml',
    'xerox',
    'xterm',
    'xcode',
    'xlink',
    'xbase',
    'xpack',
    'xsync',
    'xnet',
    'xenon',
    'xfer',
    'xform',
    'xlate',
    'xmask',
    'xport',
    'xref',
    'xsec',
    'xtra',
  ],
  y: [
    'yield',
    'yard',
    'yott',
    'yarn',
    'yoke',
    'yell',
    'year',
    'yes',
    'yellow',
    'yeti',
    'yoga',
    'yoke',
    'young',
    'your',
    'youth',
    'yurt',
  ],
  z: [
    'zero',
    'zone',
    'zoom',
    'zetta',
    'zip',
    'zulu',
    'zwave',
    'zinc',
    'zen',
    'zest',
    'zigzag',
    'zinc',
    'zip',
    'zodiac',
    'zone',
    'zoom',
    'zsh',
  ],
}

/**
 * A secondary index of the lexicon for telestic (end-letter) anchors.
 */
const LOG_LEXICON_END: Record<string, string[]> = Object.values(LOG_LEXICON)
  .flat()
  .reduce((acc: Record<string, string[]>, word: string) => {
    const lastChar = word.slice(-1).toLowerCase()
    if (!acc[lastChar]) acc[lastChar] = []
    if (!acc[lastChar].includes(word)) acc[lastChar].push(word)
    return acc
  }, {})

/**
 * A highly realistic corpus of system log messages.
 * Includes standard log levels and technical terminology.
 */
const REALISTIC_LOGS = [
  'Connection established to remote host 192.168.1.104.',
  'Database migration completed successfully in 450ms.',
  'User session initialized for UID 4029.',
  'Incoming packet validated against firewall rules.',
  'Memory allocation successful for buffer 0xAF02.',
  'File system integrity check passed for /dev/sda1.',
  "Background task 'IndexArchives' started.",
  'Resource usage within nominal limits (CPU: 12%, MEM: 44%).',
  'Authentication successful for admin via local terminal.',
  'DHCP lease renewed for interface eth0.',
  'Kernel modules loaded: crypt_aes, virtio_net.',
  'System clock synchronized with NTP pool server.',
  "Warning: High disk I/O detected on volume 'Secondary'.",
  'Optimizing database indices for faster query performance.',
  "Snapshot created for persistent volume 'Archive_Root'.",
  'SSH connection closed from 10.0.0.5 port 54322.',
  'Process 882 terminated with exit code 0.',
  "Scheduled maintenance task 'PurgeLogs' completed.",
  "New node registered in cluster 'Spire_Gamma'.",
  'API request handled: GET /v1/status (200 OK).',
  'Thermal sensors report steady state at 42 degrees Celsius.',
  'Encrypted uplink to orbital relay is now stable.',
  'Re-indexing neural pathways in the primary cortex module.',
  'Unrecognized token detected in the incoming telemetry stream.',
  'Bypassing deprecated security protocols for legacy support.',
  'Handshake verified with RSA-4096 signature.',
  'Aether flow redirected to secondary power conduits.',
  "Fragmentation levels on volume 'Ghost' have reached 15%.",
  'Neural link latency reduced to sub-millisecond range.',
  'Automatic backup of sector 9 initiated by cron-job.',
  'Diagnostic report generated for hardware revision 4.2.',
  "Virtual machine 'Sentinel-01' has entered sleep state.",
  'Packet inspection reveals encrypted payload in header.',
  'Spire-internal communication encrypted via AES-GCM.',
  'Local cache cleared for faster resource loading.',
  "Warning: Potential memory leak detected in daemon 'Monitor'.",
  'Synchronizing state between primary and redundant nodes.',
  'Uptime reached 14 days without a kernel panic.',
  'New firewall rule injected: drop all from unknown subnets.',
  'Tracing origin of the pulse signal in the deep web.',
  "Interface 'wg0' established secure tunnel to the darknet.",
  'Rotating session tokens for active administrative users.',
  'Kernel re-calibrated for high-throughput processing.',
  'Anomaly detected in the temporal synchronization loop.',
  'Purging temporary files from the system buffer.',
  "Load balancer distributing traffic to node cluster 'Alpha'.",
  'Security audit log rotated to persistent storage.',
  'Monitoring high-frequency trades in the digital exchange.',
  'System ready for high-bandwidth neural interface.',
  'Echo signal received from the silent sector of the grid.',
]

const LOG_LEVELS = [
  'INFO',
  'INFO',
  'INFO',
  'INFO',
  'INFO', // 50%
  'DEBUG',
  'DEBUG',
  'DEBUG', // 30%
  'WARN', // 10%
  'ERROR', // 7%
  'CRITICAL', // 3%
]
const SUBSYSTEMS = ['SYS', 'NET', 'AUTH', 'DB', 'FS', 'SEC']

/**
 * Generates a realistic timestamp string for a given date.
 */
const getTimestamp = (date: Date) => {
  const pad = (n: number) => n.toString().padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`
}

/**
 * Generates realistic, newline-separated system logs.
 */
export const generateThematicFiller = (
  targetWordCount: number,
  targetAlphaCount?: number,
): string => {
  const markov = RiTa.markov(2)
  markov.addText(REALISTIC_LOGS)

  const grammar = RiTa.grammar({
    start: '$sentence',
    sentence: '$subject $verb $object. | $fragment.',
    subject: 'The $adj $noun',
    adj: 'persistent | encrypted | virtual | local | remote | secondary',
    noun: 'volume | listener | gateway | socket | daemon | worker',
    verb: 'started | stopped | resumed | initialized',
    object: 'successfully | in background | on port 8080',
    fragment: '$subsystem: $adj $noun $status',
    subsystem: 'NET | SYS | AUTH | KERN | USER',
    status: 'up | down | active | pending | failed',
  })

  const lines: string[] = []
  let currentWordCount = 0
  let currentAlphaCount = 0

  const totalEntriesGuess =
    targetAlphaCount !== undefined && targetAlphaCount !== null
      ? Math.ceil(targetAlphaCount / 30)
      : Math.ceil(targetWordCount / 10)

  const fiveMinutesAgo = Date.now() - 5 * 60 * 1000
  const timeStep = (5 * 60 * 1000) / (totalEntriesGuess || 1)

  while (
    (targetAlphaCount !== undefined &&
      targetAlphaCount !== null &&
      currentAlphaCount < targetAlphaCount) ||
    ((targetAlphaCount === undefined || targetAlphaCount === null) &&
      currentWordCount < targetWordCount)
  ) {
    const level = LOG_LEVELS[Math.floor(Math.random() * LOG_LEVELS.length)]
    const sub = SUBSYSTEMS[Math.floor(Math.random() * SUBSYSTEMS.length)]

    const entryTime = new Date(fiveMinutesAgo + lines.length * timeStep + Math.random() * timeStep)
    const ts = getTimestamp(entryTime)
    const pid = Math.floor(Math.random() * 9000) + 1000

    const roll = Math.random()
    let content = ''
    if (roll < 0.6) {
      const generated = markov.generate()
      content = Array.isArray(generated) ? generated.join(' ') : (generated as string)
    } else {
      content = grammar.expand()
    }

    if (content) {
      const fullLine = `[${ts}] [${level}] [${sub}] [PID:${pid}] ${content}`

      if (targetAlphaCount !== undefined && targetAlphaCount !== null) {
        const lineAlphaCount = [...fullLine].filter((c) => /[A-Za-z]/.test(c)).length
        currentAlphaCount += lineAlphaCount
      }

      lines.push(fullLine)
      currentWordCount += fullLine.split(/\s+/).length
    }

    if (lines.length > 200) break
  }

  return lines.join('\n')
}

/**
 * Generates an acrostic or telestic log stream.
 * For Acrostics: The first word of each line starts with the secret letter.
 * For Telestics: The last word of each line ends with the secret letter.
 */
export const generateAcrostic = (
  secret: string,
  mode: 'acrostic' | 'telestic' | 'compound' = 'acrostic',
): string => {
  const letters = secret
    .toLowerCase()
    .replace(/[^a-z]/g, '')
    .split('')

  // Simulation window for timestamps
  const fiveMinutesAgo = Date.now() - 5 * 60 * 1000
  const timeStep = (5 * 60 * 1000) / (letters.length || 1)

  // Pre-build Markov model once for efficiency
  const markov = RiTa.markov(2)
  markov.addText(REALISTIC_LOGS)

  const lines = letters.map((char, index) => {
    const entryTime = new Date(fiveMinutesAgo + index * timeStep + Math.random() * timeStep)
    const ts = getTimestamp(entryTime)
    const pid = Math.floor(Math.random() * 9000) + 1000
    const level = LOG_LEVELS[Math.floor(Math.random() * LOG_LEVELS.length)]
    const sub = SUBSYSTEMS[Math.floor(Math.random() * SUBSYSTEMS.length)]

    // Find words for the constraints
    let anchorStart = ''
    let anchorEnd = ''

    // 1. Try our curated Log Lexicon first for realism
    const isTrailing = mode === 'telestic'
    if (mode === 'acrostic' || mode === 'compound') {
      const pool = LOG_LEXICON[char] || []
      if (pool.length > 0) anchorStart = pool[Math.floor(Math.random() * pool.length)]
    }
    if (isTrailing || mode === 'compound') {
      const pool = (LOG_LEXICON_END[char] || []).filter((w) => w !== anchorStart)
      if (pool.length > 0) anchorEnd = pool[Math.floor(Math.random() * pool.length)]
    }

    // 2. Fallback to RiTa if curated list is empty or for extra variety (20% chance)
    if ((mode === 'acrostic' || mode === 'compound') && (!anchorStart || Math.random() < 0.2)) {
      const candidates = RiTa.searchSync(new RegExp(`^${char}`, 'i'), {
        limit: 50,
        pos: 'nn|jj|vb',
      })
      if (candidates.length > 0) {
        const technical = candidates.filter((w) =>
          /sync|node|data|crypt|core|pulse|link|void|dark|neon|host|port|scan|test|auth|admin|user|file/i.test(
            w,
          ),
        )
        const pool = technical.length > 0 ? technical : candidates
        anchorStart = pool[Math.floor(Math.random() * pool.length)]
      }
    }
    if ((isTrailing || mode === 'compound') && (!anchorEnd || Math.random() < 0.2)) {
      const candidates = RiTa.searchSync(new RegExp(`${char}$`, 'i'), {
        limit: 50,
        pos: 'nn|jj|vb',
      }).filter((w) => w !== anchorStart)
      if (candidates.length > 0) {
        const technical = candidates.filter((w) =>
          /sync|node|data|crypt|core|pulse|link|void|dark|neon|host|port|scan|test|auth|admin|user|file/i.test(
            w,
          ),
        )
        const pool = technical.length > 0 ? technical : candidates
        anchorEnd = pool[Math.floor(Math.random() * pool.length)]
      }
    }

    if (!anchorStart) anchorStart = char.toUpperCase()
    if (!anchorEnd) anchorEnd = char.toUpperCase()

    // Generate filler that sounds like the end of a log line
    const generated = markov.generate()
    let filler =
      (Array.isArray(generated) ? generated.join(' ') : (generated as string)) ||
      'protocol execution completed'

    // Clean filler to remove leading timestamps if Markov hallucinated them
    filler = filler.replace(/^(\[[^\]]+\]\s*)+/, '')

    if (mode === 'acrostic') {
      return `[${ts}] [${level}] [${sub}] [PID:${pid}] ${anchorStart.toUpperCase()} ${filler}`
    } else if (mode === 'telestic') {
      return `[${ts}] [${level}] [PID:${pid}] ${sub}: ${filler} ${anchorEnd.toUpperCase()}`
    } else {
      // Compound
      return `[${ts}] [${level}] [${sub}] [PID:${pid}] ${anchorStart.toUpperCase()} ${filler} ${anchorEnd.toUpperCase()}`
    }
  })

  return lines.join('\n')
}

/**
 * Generates cover text specifically for Bacon's Encoding.
 */
export const generateBaconCover = (bitLength: number): string => {
  return generateThematicFiller(0, bitLength)
}
