name: Use Shared Action to Publish

on:
  release:
    types:
      - published
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shared Publish to NPM
        uses: McCann-Hub/create-typescript-template/.github/shared/npm/publish@master
        with:
          node_version: 22.x
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  upload-to-release:
    runs-on: ubuntu-latest
    needs: publish_to_npm # Only upload to release if publish succeeds
    permissions:
      contents: write # Required to upload assets to the release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: 'npm run build:lib'

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: lib/*

  publish_to_ghpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shared Publish to GHPR
        uses: McCann-Hub/create-typescript-template/.github/shared/ghpr/publish@master
        with:
          node_version: 22.x
        env:
          GHPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_to_jsr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shared Publish to JSR
        if: ${{ hashFiles('deno.json') != '' }}
        uses: McCann-Hub/create-typescript-template/.github/shared/jsr/publish@master
        with:
          deno_version: 2.x
